import { chromium } from "playwright-core";
import { readFileSync } from "node:fs";
import JSZip from "jszip";

const baseUrl = process.env.APP_URL || "http://127.0.0.1:5174";
const reportPath = process.env.HEALTH_REPORT;
if (!reportPath) throw new Error("请通过 HEALTH_REPORT 指定测试用 PDF 路径");
const browser = await chromium.launch({ headless: true, executablePath: "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome" });
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, acceptDownloads: true });
const errors = [];
page.on("pageerror", (error) => errors.push(error.message));
page.on("console", (message) => { if (message.type() === "error") errors.push(message.text()); });

await page.goto(baseUrl, { waitUntil: "networkidle" });
await page.screenshot({ path: "/tmp/xhs-wizard-home.png", fullPage: true });
if (await page.getByText("企业 AI 应用趋势", { exact: true }).count()) throw new Error("首页仍显示示例任务");
await page.locator('input[type="file"]').setInputFiles(reportPath);
await page.locator('[aria-label="文案与封面"]').waitFor({ timeout: 60_000 });
await page.screenshot({ path: "/tmp/xhs-wizard-copy.png", fullPage: true });
await page.getByRole("button", { name: /下一步：选择报告图片/ }).click();
await page.getByRole("heading", { name: "选择真正要发布的图片" }).waitFor();
await page.locator('[data-asset-status="ready"]').waitFor({ timeout: 120_000 });
const reportAssets = await page.locator(".asset-card").count();
if (reportAssets < 1) throw new Error("真实报告没有生成整页图片");
await page.getByRole("button", { name: /从页面手动裁切/ }).click();
await page.getByRole("heading", { name: "框选要发布的图表区域" }).waitFor();
await page.getByRole("button", { name: /加入候选图片/ }).click();
await page.getByRole("heading", { name: "框选要发布的图表区域" }).waitFor({ state: "hidden" });
const assetsAfterCrop = await page.locator(".asset-card").count();
if (assetsAfterCrop !== reportAssets + 1) throw new Error(`手动裁切未加入候选：${assetsAfterCrop}`);
await page.screenshot({ path: "/tmp/xhs-wizard-images.png", fullPage: true });
await page.getByRole("button", { name: /下一步：最终审核/ }).click();
await page.getByRole("heading", { name: "确认内容，再同步发布" }).waitFor();
await page.screenshot({ path: "/tmp/xhs-wizard-review.png", fullPage: true });
const finishButton = page.getByRole("button", { name: /导出内容包/ });
if (!await finishButton.isEnabled()) {
  const checks = await page.locator(".review-checks").innerText().catch(() => "");
  throw new Error(`完成按钮不可用：${checks}`);
}
const downloadPromise = page.waitForEvent("download");
await finishButton.click();
const download = await downloadPromise.catch(async (error) => {
  const toast = await page.locator(".toast").allInnerTexts().catch(() => []);
  throw new Error(`${error.message}; toast=${toast.join(" | ")}; pageErrors=${errors.join(" | ")}`);
});
const downloadPath = await download.path();
if (!downloadPath) throw new Error("没有拿到导出内容包路径");
const exportedZip = await JSZip.loadAsync(readFileSync(downloadPath));
const exportedNames = Object.keys(exportedZip.files);
if (exportedNames.some((name) => /\.(?:json|md|markdown)$/i.test(name))) throw new Error(`导出包仍包含 JSON 或 Markdown：${exportedNames.join(", ")}`);
if (!exportedNames.includes("03-发布文案.txt") || !exportedNames.includes("04-图片顺序.txt")) throw new Error(`导出包缺少纯文本文件：${exportedNames.join(", ")}`);
const exportedPost = (await exportedZip.file("03-发布文案.txt").async("string")).replace(/^\uFEFF/, "");
if (!exportedPost.includes("\n\n") || /^\s*[\[{`]/.test(exportedPost)) throw new Error("发布文案不是可直接粘贴的纯文本");
if (!await page.getByRole("button", { name: "复制纯文本" }).isVisible()) throw new Error("最终审核页缺少一键复制纯文本入口");
await page.locator(".history-task", { hasText: "已完成" }).waitFor();
await page.getByRole("button", { name: "新建内容", exact: true }).click();
await page.locator(".history-task", { hasText: "已完成" }).locator("button").first().click();
await page.getByRole("heading", { name: "确认内容，再同步发布" }).waitFor();
await page.waitForTimeout(1100);
await page.getByRole("button", { name: "上传首页" }).click();
if (!await page.locator(".history-task", { hasText: "已完成" }).isVisible()) throw new Error("已完成任务被自动保存回退为草稿");
await page.getByRole("button", { name: "收起创作台" }).click();
if (!await page.locator(".wizard-shell").evaluate((element) => element.classList.contains("sidebar-collapsed"))) throw new Error("侧栏未收起");
const expandBox = await page.getByRole("button", { name: "展开创作台" }).boundingBox();
if (!expandBox || expandBox.width < 40 || expandBox.height < 40) throw new Error("展开创作台按钮触控区域过小");
await page.close();

let parsedPdfAssets = null;
const pdfFixture = reportPath;
const uploadPage = await browser.newPage({ viewport: { width: 1280, height: 900 } });
await uploadPage.goto(baseUrl, { waitUntil: "networkidle" });
await uploadPage.locator('input[type="file"]').setInputFiles(pdfFixture);
await uploadPage.locator('[aria-label="文案与封面"]').waitFor({ timeout: 60000 });
const firstTitleInput = uploadPage.getByRole("textbox", { name: "标题方案 1", exact: true });
await firstTitleInput.fill("自动保存测试标题");
await uploadPage.locator(".history-list").getByRole("button", { name: /健康饮料市场消费趋势洞察/ }).first().click();
if (await firstTitleInput.inputValue() !== "自动保存测试标题") throw new Error("重复点击当前任务覆盖了未保存编辑");
await uploadPage.waitForTimeout(1200);
await uploadPage.getByRole("button", { name: "上传首页" }).click();
await uploadPage.locator(".history-list").getByRole("button", { name: /健康饮料市场消费趋势洞察/ }).first().click();
if (await firstTitleInput.inputValue() !== "自动保存测试标题") throw new Error("历史任务没有恢复自动保存的标题");
await uploadPage.getByRole("button", { name: /下一步：选择报告图片/ }).click();
await uploadPage.getByRole("heading", { name: "选择真正要发布的图片" }).waitFor();
await uploadPage.locator('[data-asset-status="ready"]').waitFor({ timeout: 60000 });
parsedPdfAssets = await uploadPage.locator(".asset-card").count();
if (parsedPdfAssets < 1) throw new Error("真实 PDF 后台图片提取没有产出候选图");
if (!await uploadPage.getByRole("button", { name: /从页面手动裁切/ }).isVisible()) throw new Error("真实 PDF 缺少手动裁切入口");
await uploadPage.getByRole("button", { name: /从页面手动裁切/ }).click();
await uploadPage.getByRole("button", { name: /加入候选图片/ }).click();
await uploadPage.getByRole("heading", { name: "框选要发布的图表区域" }).waitFor({ state: "hidden", timeout: 30000 });
const cropImage = uploadPage.locator(".asset-card img").last();
await cropImage.evaluate((image) => image.complete && image.naturalWidth > 0 || new Promise((resolve) => image.addEventListener("load", resolve, { once: true })));
const highResCropWidth = await cropImage.evaluate((image) => image.naturalWidth);
if (highResCropWidth < 1000) throw new Error(`PDF 手动裁切仍然低清：${highResCropWidth}px`);
await uploadPage.close();

const wordPage = await browser.newPage({ viewport: { width: 1280, height: 900 } });
await wordPage.goto(baseUrl, { waitUntil: "networkidle" });
await wordPage.locator('input[type="file"]').setInputFiles("/tmp/xhs-word-report.docx");
await wordPage.locator('[aria-label="文案与封面"]').waitFor({ timeout: 60000 });
await wordPage.getByRole("button", { name: /下一步：选择报告图片/ }).click();
await wordPage.getByRole("heading", { name: "选择真正要发布的图片" }).waitFor();
const parsedWordAssets = await wordPage.locator(".asset-card").count();
if (parsedWordAssets < 1) throw new Error("Word 原图未提取");
await wordPage.close();

const mobilePage = await browser.newPage({ viewport: { width: 390, height: 844 } });
await mobilePage.goto(baseUrl, { waitUntil: "networkidle" });
await mobilePage.getByRole("button", { name: "查看历史任务" }).click();
if (!await mobilePage.locator(".mobile-history-drawer").isVisible()) throw new Error("移动端历史任务抽屉未打开");
await mobilePage.close();

console.log(JSON.stringify({ steps: ["upload", "copy", "images", "review"], reportAssets, assetsAfterCrop, parsedPdfAssets, highResCropWidth, parsedWordAssets, mobileHistory: true, exportFile: download.suggestedFilename(), errors }, null, 2));
await browser.close();
